import turtle
def draw_circle(size):
    turtle.right(90)
    turtle.up()
    turtle.forward(size/4)
    turtle.left(90)
    turtle.down()
    turtle.fillcolor('red')
    turtle.begin_fill()
    turtle.circle(size/4)
    turtle.end_fill()
    turtle.up()
    turtle.left(90)
    turtle.forward(size/4)
    turtle.right(90)
    turtle.down()

def draw_bowtie1(size):
    turtle.pencolor('blue')
    turtle.left(30)
    turtle.forward(size)
    turtle.right(120)
    turtle.forward(size)
    turtle.right(120)
    turtle.forward(2*size)
    turtle.left(120)
    turtle.forward(size)
    turtle.left(120)
    turtle.forward(size)
    turtle.right(30)
    draw_circle(size)

def draw_bowtie(size,depth):
    if(depth != 0):
        draw_bowtie1(size)
        turtle.up()
        turtle.left(30)
        turtle.forward(2*size)
        turtle.down()
        draw_bowtie(size/3,depth-1)
        turtle.up()
        turtle.backward(2*size)
        turtle.left(120)
        turtle.forward(2*size)
        turtle.down()
        draw_bowtie(-size/3,depth-1)
        turtle.up()
        turtle.backward(size*2)
        turtle.right(150)

def init():
    turtle.setup(600,600)
    return(int(input('What depth would you like to run the program until (depth>=1)')))
draw_bowtie(600/6,init())
